spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nowaste
spring.datasource.username=postgres
spring.datasource.password=davi123veiga

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# Upload
nowaste.upload.dir=./uploads
